site_name: HedgeDoc
site_url: https://docs.hedgedoc.org
repo_url: https://github.com/hedgedoc/hedgedoc
site_description: 'HedgeDoc Documentation'
site_author: 'HedgeDoc Developers'
docs_dir: content
edit_uri: https://github.com/hedgedoc/hedgedoc/edit/master/docs/content/
nav:
  - Home: index.md
  - Interface:
      Toolbar: interface/toolbar.md
  - Developer:
      - '2.0 Development': dev/2.0.md
      - 'User Profiles & Authentication': dev/authentication.md
      - Configuration: dev/config.md
      - 'Documentation': dev/documentation.md
  - FAQ: https://hedgedoc.org/faq
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
theme:
  name: 'material'
  language: en
  favicon: images/favicon.png
  logo: images/logo.svg
  palette:
    scheme: light
    primary: 'hedgedoc'
    accent: 'hedgedoc'
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
  font: false

extra_css:
  - theme/styles/hedgedoc-custom.css
  - theme/styles/roboto.css
